adding spinner
Meonix/NewsApp pull request #2
Opened 2020-09-23 02:22 UTC by Meonix

2020-09-23 02:33 UTC, enpiech requested changes

2020-09-23 02:33 UTC, enpiech commented on app/src/main/java/com/mionix/newsapp/repo/PopularNewsRepo.kt
> +    suspend fun getPopularNews(page :Int,country:String): Response<ListPopularNews> {
Thêm khoảng trắng ' ' sau dấu phẩy

2020-09-23 02:33 UTC, enpiech commented on app/src/main/java/com/mionix/newsapp/ui/MainActivity.kt
> +        val NULL_VIEW_GROUP = null
Dùng null mịa đi 👎

2020-09-23 02:33 UTC, enpiech commented on app/src/main/java/com/mionix/newsapp/ui/Popular/PopularFragment.kt
> +        const val ARGENTINA = "Argentina"
Tách đống này ra 1 class khác hoặc 1 file khác - aka Region

2020-09-23 02:33 UTC, enpiech commented on app/src/main/java/com/mionix/newsapp/ui/Popular/PopularFragment.kt
> +        const val ARGENTINA = "Argentina"
Có thể là 1 class Region, có 1 field để chứa 'ISO_3166_1_ARGENTINA', xong đẩy nguyên đống này vào trong companion của class Region đó

2020-09-23 02:33 UTC, enpiech commented on app/src/main/java/com/mionix/newsapp/ui/Popular/PopularFragment.kt
> +        const val ARGENTINA = "Argentina"
1 field chứa name nữa

2020-09-23 02:33 UTC, enpiech commented on app/src/main/java/com/mionix/newsapp/ui/Popular/PopularFragment.kt
> +        // Way 1 is Using CoordinatorLayout AppBarLayout and CollapsingToolbarLayout
Way 1 vậy có way 2 không?

2020-09-23 02:33 UTC, enpiech commented on app/src/main/res/layout/view_filter.xml
> +        android:textSize="20sp"
Đem vô dimen

2020-09-23 02:33 UTC, enpiech commented on app/src/main/res/layout/fragment_popular.xml
> +                android:layout_height="50dp"
dimen

2020-09-23 02:33 UTC, enpiech commented on app/src/main/res/layout/activity_main.xml
> +                custom:tabIndicatorHeight="4dp"
dimen

2020-09-23 03:37 UTC, Meonix commented on app/src/main/java/com/mionix/newsapp/ui/Popular/PopularFragment.kt
> +        // Way 1 is Using CoordinatorLayout AppBarLayout and CollapsingToolbarLayout
có nhưng mà bê đống code comment vào project khác để lưu r :)))

2020-09-24 03:43 UTC, enpiech approved these changes

2020-09-24 03:43 UTC, enpiech commented on app/src/main/java/com/mionix/newsapp/ui/MainActivity.kt
> +    private fun makeBlur(it: Boolean) {
it nghĩa là gì? nên đặt là is + Adj cho dễ hiểu, ex: isTouched

2020-09-24 03:43 UTC, enpiech commented on app/src/main/java/com/mionix/newsapp/ui/MainActivity.kt
> +            true -> {
true false thì if else là đủ rồi

2020-09-24 03:43 UTC, merged