Feature/adding popular news detail
Meonix/NewsApp pull request #6
Opened 2020-10-27 04:42 UTC by Meonix

2020-10-27 07:15 UTC, enpiech requested changes

2020-10-27 07:15 UTC, enpiech commented on app/src/main/java/com/mionix/newsapp/model/DataProfile.kt
> +data class DataProfile (val image:String?,val name :String?)
String để empty "" cũng được mà? Có nhất thiết phải là optional không?

2020-10-27 07:15 UTC, enpiech commented on app/src/main/java/com/mionix/newsapp/repo/NewsDetailRepo.kt
> +    private val _listComment = MutableLiveData<MutableList<Comment>>()
Hạn chế dùng livedata ở dưới layer data này, nó không được thiết kế để xử lý data. Nếu work thì có thể để sau này refactor cũng được

2020-10-27 07:15 UTC, enpiech commented on app/src/main/java/com/mionix/newsapp/ui/popular/NewsDetail.kt
> +        mCommentAdapter
Cái này có tác dụng gì?

2020-10-27 07:28 UTC, Meonix commented on app/src/main/java/com/mionix/newsapp/model/DataProfile.kt
> +data class DataProfile (val image:String?,val name :String?)
có chứ khi mà null thì phải báo null để xử lý khác chứ

2020-10-28 01:14 UTC, Meonix commented on app/src/main/java/com/mionix/newsapp/model/DataProfile.kt
> +data class DataProfile (val image:String?,val name :String?)
có mà tại vì khi name voi image null thì xử lý khác

2020-10-28 01:39 UTC, enpiech approved these changes

2020-10-28 01:39 UTC, merged